export type Pipeline={pipeline_id:number;pipeline_name:string;organization_name:string|null;project_name:string|null}
export type Options={organizations:string[];projects:string[];pipelines:Pipeline[]}
export type Summary={pipeline_id:number|null;window_days:number;total_runs:number;successful_runs:number;failed_runs:number;success_rate_pct:number;failure_rate_pct:number;degraded_runs?:number;average_duration_seconds:number|null;p90_duration_seconds:number|null;average_queue_seconds:number|null;stages:Array<{stage_name:string;avg_duration_seconds:number;samples:number;failed_count:number}>}
export type Trends={build_trend:Array<{run_id:number;run_date:string;pipeline_id:number;pipeline_name:string;duration_seconds:number;result:string|null}>;daily_trend:Array<{run_date:string;pipeline_id:number;pipeline_name:string;avg_duration_seconds:number|null;p90_duration_seconds:number|null}>;stage_trend:Array<{run_date:string;stage_name:string;avg_duration_seconds:number}>}
export type Runs={page:number;page_size:number;total_count:number;total_pages:number;items:Array<{run_id:number;pipeline_id:number;pipeline_name:string;organization_name:string;project_name:string;source_branch:string|null;build_number:string|null;start_time:string|null;finish_time:string|null;result:string|null;duration_seconds:number|null;is_degraded:boolean;data_quality:string}>}
export type Recommendation={id:number|null;pipeline_id:number;category:string;severity:string;stage_name:string;task_name:string|null;recommendation:string;evidence:string;generated_at:string|null}
export type TimelineRecord={id:number;record_id:string;stage_name:string|null;job_name?:string|null;task_name?:string|null;pool_name?:string|null;agent_name:string|null;start_time:string|null;finish_time:string|null;duration_seconds:number|null;result:string|null;retry_count:number;failure_log_excerpt?:string|null}
export type RunAnalysis={run:{run_id:number;pipeline_id:number;pipeline_name:string;organization_name:string;project_name:string;source_branch:string|null;source_version:string|null;requested_by:string|null;queue_time:string|null;start_time:string|null;finish_time:string|null;result:string|null;data_quality:string;duration_seconds:number|null};stages:TimelineRecord[];jobs:TimelineRecord[];tasks:TimelineRecord[];metrics:{run_duration_seconds:number;stage_count:number;job_count:number;task_count:number;failed_records:number;stage_duration_total_seconds:number;job_duration_total_seconds:number;task_duration_total_seconds:number;queue_seconds:number|null;longest_stage:TimelineRecord|null;longest_job:TimelineRecord|null;longest_task:TimelineRecord|null}}

export type AdoProject={id:string;name:string}
export type AdoPipeline={id:number;name:string;project_id:string|null;project_name:string|null}
export type AdoConnection={organization:string;projects:AdoProject[];pipelines:AdoPipeline[]}
