line-length = 140
target-version = "py311"
extend-exclude = ["**/venv/**", "**/.venv*/**", "**/node_modules/**", "**/publish/**", "**/scratch/**", "**/logs-extracted/**", "**/frontend/**"]

[lint.per-file-ignores]
"**/tests/**" = ["S101", "S105", "S106", "S311", "PLR2004", "PLR0913"]
"**/quality_gate/**" = ["S101", "S603", "S607", "PLR2004", "PLR0913"]
